name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-linters:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set Up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Node.js Dependencies
        run: npm ci

      - name: Run Linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
